// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfGdoQVtJMi23OwWhnQBm42H--7zysx0',
    appId: '1:367214870029:web:49753b8ebe03934f825f44',
    messagingSenderId: '367214870029',
    projectId: 'doctor-appointment-962c9',
    authDomain: 'doctor-appointment-962c9.firebaseapp.com',
    storageBucket: 'doctor-appointment-962c9.appspot.com',
    measurementId: 'G-5Y6HN5THYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLCYNEhLghvDGPi8dNGRWKMZQiB_iozE',
    appId: '1:367214870029:android:eb039f2cd5a733fb825f44',
    messagingSenderId: '367214870029',
    projectId: 'doctor-appointment-962c9',
    storageBucket: 'doctor-appointment-962c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pU0Cxc3Rbcp2gxkTgT-0U3gZMR8HbbY',
    appId: '1:367214870029:ios:2e895e56ec4d35d7825f44',
    messagingSenderId: '367214870029',
    projectId: 'doctor-appointment-962c9',
    storageBucket: 'doctor-appointment-962c9.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pU0Cxc3Rbcp2gxkTgT-0U3gZMR8HbbY',
    appId: '1:367214870029:ios:2e895e56ec4d35d7825f44',
    messagingSenderId: '367214870029',
    projectId: 'doctor-appointment-962c9',
    storageBucket: 'doctor-appointment-962c9.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRfGdoQVtJMi23OwWhnQBm42H--7zysx0',
    appId: '1:367214870029:web:a2fea2128d4d89a4825f44',
    messagingSenderId: '367214870029',
    projectId: 'doctor-appointment-962c9',
    authDomain: 'doctor-appointment-962c9.firebaseapp.com',
    storageBucket: 'doctor-appointment-962c9.appspot.com',
    measurementId: 'G-V0T0TTEM9M',
  );

}